### ISSUE TITLE
Datakonsumption via integration

### ISSUE THREAD

**Issue by FredrikElliot** [studio27se/ehub#19]
Vi lägger till en dataattribut för att ställa in om en driftstörning ska visas på webben eller inte. Alla driftstörningar skapas med "ja" som standard. Ändringen av detta görs via en kryssruta i webbapplikationen.

Vi lägger till två filter i endpointet för att hämta alla driftstörningar, så att integrationen med hemsidan kan filtrera ut endast det den behöver.
Filtrerna är:
- faktisk avsluttid
- showonweb

Vi separerar IDt ifrån namnet i namn-attributen. Istället implementerar vi en sammanslagning av dessa i frontends.

- [x] studio27se/ehub-backend-api#191
- [x] studio27se/ehub-backend-api#192
- [x] studio27se/ehub-backend-api#193
- [x] studio27se/ehub-app-ionic#415
- [x] studio27se/ehub-webapp#226
- [x] studio27se/ehub-webapp#227
- [x] studio27se/ehub-backend-api#194

**Comment by FredrikElliot** [comment]
Efter diskussion med Christian bestämdes det att vi istället implementerar en separat endpoint for att hämta innehåll till webben, med de fält Christian har specat. Vi autofiltrerar då också på showonweb.

- [ ] New endpoint for fetchin outage data for web

**Comment by christian-levin** [comment]
Låter bra 👍

**Comment by FredrikElliot** [comment]
Hej @christian-levin
Nu finns integrations-endpointet uppe för datakonsumtion. Du hittar den på `https://api.ehub.se/outages/web/` och kan använda filter för `?actualEnd=yyyy-mm-ddThh:mm:ss`. Endpointet sorterar automatiskt ut endast de driftstörningar som har `showonweb : true`. Även separation av namn är justerat för framtida driftstörningar. Den data som ligger just nu har dock inte justerats, så gamla störningar kommer fortfarande ha det gamla formatet i namn-strängen.

Vi fortsätter med implementeringen av att kunna justera störningars showonweb-attribut i webbapplikationen och håller issuet öppet till det är klart.

**Comment by FredrikElliot** [comment]
@christian-levin @MonaAdawi
Nu är även möjligheten att justera "show on web" ifrån webbapplikationen. Checkrutan är tillagd under första fliken när man skapar/redigerar en driftstörning. 

![image](https://github.com/studio27se/ehub/assets/9091372/a312c966-d0f9-41bd-a80b-e0f2595d421c)

**Comment by christian-levin** [comment]
Hej, vi hittade en sak när vi använder ?actualEnd=yyyy-mm-ddThh:mm:ss som filterparameter. Tanken är ju att endast hämta hem de senaste driftstörningarna. Ex vi sätter datumet till 4 månader bakåt i tiden. Problemet vi upptäckt är att om en driftstörning inte har något actualEnd = null så följer de inte med ut i listan. Så kan man justera filtret att ta med de som har actualEnd = null?

**Comment by FredrikElliot** [comment]
Absolut! Jag öppnar ett separat issue för det!

- [ ] https://github.com/studio27se/ehub/issues/65
